### ISSUE TITLE
Topic sorting

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#919] opened 2017-03-25 00:46 UTC
It should be possible for topics to be sorted in order by number, instead of in the order that topics were added to the signup sheet.  I just added E1731 to a spreadsheet that had E1732 to E1743, and E1731 is at the bottom of all of them.

**Comment by ferryxo** [comment] 2017-06-07 16:26
duplicate of #926

**Closed by ferryxo** 2017-06-07 16:26 UTC
