### ISSUE TITLE
Instructor can't participate in an assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1072] opened 2017-10-29 13:30 UTC
During the TLT Group "designated learner" session on 26 Oct 2017.  we found that an instructor could not also be a participant in an assignment.  An instructor who tried to click on an assignment in the task list got a message saying that a eula action is not permitted for an instructor.

**Comment by Rui5** [comment] 2017-11-01 20:10
Cannot reproduce this issue. I think fixing issue #1064 will help with this issue.

**Comment by ZachariahMathews** [comment] 2019-02-21 02:18
Fixed by pull request #1323

**Closed by ZachariahMathews** 2019-02-21 02:18 UTC
