### ISSUE TITLE
Creating a questionnaire with a blank name causes a walkback

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1195] opened 2018-07-25 17:17 UTC
If someone tries to create a questionnaire and fails to give it a name (s)he should be prompted to enter a name, rather than having a Rails error be reported.

**Comment by ZachariahMathews** [comment] 2019-02-07 06:10
Duplicate of Issue #1210 Creating a questionnaire crashes if no title is specified?

**Closed** 2019-02-21 02:16 UTC
