### ISSUE TITLE
When participants are added from the UI, an error is reported

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1189] opened 2018-06-13 17:45 UTC
I just tried adding participants manually to "Assignment with duplicated directory".  Each time I received a warning, "User does not exist or has already been added."  But then I listed the users, and found out that they _were_ on the participants list.  So there seems to be a bug in manually adding participants.

**Comment by ZachariahMathews** [comment] 2019-02-21 02:19
Duplicate of #1072

**Closed by ZachariahMathews** 2019-02-21 02:19 UTC
